[versions]
coroutines = { strictly = "1.6.1-native-mt" }
jackson = { prefer = "2.13.2" }
reflect = { prefer = "1.7.0" }
ton = { strictly = "e279451600" }
logging = { prefer = "2.1.23" }
logback = { prefer = "1.2.11" }
logstash-logback-encoder = { prefer = "7.2" }
jakarta = { prefer = "2.1.1" }
micronaut = { prefer = "3.5.1" }
micronaut-data = { prefer = "3.4.2" }
micronaut-flyway = { prefer = "5.3.0" }
micronaut-kotlin = { prefer = "3.2.2" }
micronaut-openapi = { prefer = "4.3.0" }
micronaut-sql = { prefer = "4.6.1" }
micronaut-micrometer = { prefer = "4.3.0" }
swagger = { prefer = "2.2.1" }
spotbugs = { prefer = "4.7.1" }
postgresql = { prefer = "42.4.0" }
kotlin = "1.7.0"
shadow = "7.1.2"
micronaut-plugins = "3.4.1"
jib = "3.2.1"

[libraries]
# Core
reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "reflect" }
ton = { group = "com.github.andreypfau.ton-kotlin", name = "ton-kotlin", version.ref = "ton" }

# Coroutines
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "coroutines" }
coroutines-reactive = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactive", version.ref = "coroutines" }

# Data
jackson = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }

# Logging
logging = { group = "io.github.microutils", name = "kotlin-logging", version.ref = "logging" }
logback-core = { group = "ch.qos.logback", name = "logback-core", version.ref = "logback" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
logstash-logback-encoder = { group = "net.logstash.logback", name = "logstash-logback-encoder", version.ref = "logstash-logback-encoder" }

# Annotations
jakarta-annotations = { group = "jakarta.annotation", name = "jakarta.annotation-api", version.ref = "jakarta" }
swagger-annotations = { group = "io.swagger.core.v3", name = "swagger-annotations", version.ref = "swagger" }
spotbugs-annotations = { group = "com.github.spotbugs", name = "spotbugs-annotations", version.ref = "spotbugs" }

###
# Micronaut
###

# Core
micronaut-jackson-databind = { group = "io.micronaut", name = "micronaut-jackson-databind", version.ref = "micronaut" }
micronaut-kotlin-runtime = { group = "io.micronaut.kotlin", name = "micronaut-kotlin-runtime", version.ref = "micronaut-kotlin" }
micronaut-kotlin-extensions = { group = "io.micronaut.kotlin", name = "micronaut-kotlin-extension-functions", version.ref = "micronaut-kotlin" }
micronaut-validation = { group = "io.micronaut", name = "micronaut-validation", version.ref = "micronaut" }

# Micronaut kapt-related
micronaut-data-processor = { group = "io.micronaut.data", name = "micronaut-data-processor", version.ref = "micronaut-data" }
micronaut-http-validation = { group = "io.micronaut", name = "micronaut-http-validation", version.ref = "micronaut" }
micronaut-openapi = { group = "io.micronaut.openapi", name = "micronaut-openapi", version.ref = "micronaut-openapi" }

# Http
micronaut-http-client = { group = "io.micronaut", name = "micronaut-http-client", version.ref = "micronaut" }
micronaut-http-server-netty = { group = "io.micronaut", name = "micronaut-http-server-netty", version.ref = "micronaut" }

# Data
micronaut-data-jdbc = { group = "io.micronaut.data", name = "micronaut-data-jdbc", version.ref = "micronaut-data" }
micronaut-flyway = { group = "io.micronaut.flyway", name = "micronaut-flyway", version.ref = "micronaut-flyway" }
micronaut-jdbc-hikari = { group = "io.micronaut.sql", name = "micronaut-jdbc-hikari", version.ref = "micronaut-sql" }

# Extra
micronaut-micrometer-core = { group = "io.micronaut.micrometer", name = "micronaut-micrometer-core", version.ref = "micronaut-micrometer" }
micronaut-micrometer-annotations = { group = "io.micronaut.micrometer", name = "micronaut-micrometer-annotation", version.ref = "micronaut-micrometer" }

[bundles]
annotations = ["jakarta-annotations", "swagger-annotations", "spotbugs-annotations"]
coroutines = ["coroutines-core", "coroutines-reactive"]
data-runtime = ["postgresql"]
logging = ["logging", "logstash-logback-encoder"]
logging-runtime = ["logback-core", "logback-classic"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
micronaut-application = { id = "io.micronaut.application", version.ref = "micronaut-plugins" }
